CUDA_VISIBLE_DEVICES=0,1 python projects/sav_finetune/train_sav.py \
    --train-frames /home/lji/SAM/datasets/sa-v/sav_train/JPEGImages_24fps \
    --train-annotations /home/lji/SAM/datasets/sa-v/sav_train/Annotations_manual_JSON \
    --val-frames /home/lji/SAM/datasets/sa-v/sav_val/JPEGImages_24fps \
    --val-annotations /home/lji/SAM/datasets/sa-v/sav_val/Annotations_6fps\
    --val-file-list /home/lji/SAM/datasets/sa-v/sav_val/sav_val.txt \
    --checkpoint /home/lji/SAM/sam2/checkpoints/sam2.1_hiera_small.pt \
    --config projects/sav_finetune/configs/sam2.1_hiera_s_sav_finetune.yaml \
    --experiment-dir /home/lji/SAM/sam2/projects/sav_finetune/exps/small \
    --gpus 2 \
    --grad-log-every 100 \
    --seed 42